[toolchain]
anchor_version = "0.29.0" 

[features]
resolution = true
skip-lint = false

[programs.localnet]
merkle_tree = "FuGmDsT3CEkML6gpLUv9mdsdQG3T4J2y4xY8GH2Le6Sn"
[programs.devnet]
merkle_tree = "FuGmDsT3CEkML6gpLUv9mdsdQG3T4J2y4xY8GH2Le6Sn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "ts-node migrations/init.ts"
addLeaf = "ts-node scripts/addLeaf.ts"
